# Generated by Django 2.1.7 on 2019-04-15 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('village', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(null=True)),
                ('Marriage_status', models.CharField(max_length=20, null=True)),
                ('language', models.CharField(max_length=20, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('community_status', models.CharField(max_length=20, null=True)),
                ('farm_area', models.CharField(max_length=20, null=True)),
                ('crop_type', models.CharField(max_length=20, null=True)),
                ('past_harvest', models.CharField(max_length=20, null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jica.District')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('login_id', models.CharField(max_length=20, null=True, unique=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jica.District')),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('season', models.CharField(max_length=20, null=True)),
                ('area', models.CharField(max_length=20, null=True)),
                ('rice_type', models.CharField(max_length=20, null=True)),
                ('sowing_date', models.CharField(max_length=20, null=True)),
                ('sowing_type', models.CharField(max_length=20, null=True)),
                ('planting_type', models.CharField(max_length=20, null=True)),
                ('levelling', models.CharField(max_length=20, null=True)),
                ('ridge', models.CharField(max_length=20, null=True)),
                ('watercourse_state', models.CharField(max_length=20, null=True)),
                ('fertilizer', models.CharField(max_length=20, null=True)),
                ('fertilizer1_type', models.CharField(max_length=20, null=True)),
                ('fertilizer1_amount', models.CharField(max_length=20, null=True)),
                ('fertilizer2_type', models.CharField(max_length=20, null=True)),
                ('fertilizer2_amount', models.CharField(max_length=20, null=True)),
                ('weed_condition', models.CharField(max_length=20, null=True)),
                ('total_weed_times', models.CharField(max_length=20, null=True)),
                ('harvest_date', models.CharField(max_length=20, null=True)),
                ('harvest_amount', models.CharField(max_length=20, null=True)),
                ('note', models.CharField(max_length=20, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=20, null=True)),
                ('season_id', models.CharField(max_length=20, null=True)),
                ('season', models.CharField(max_length=20, null=True)),
                ('area', models.CharField(max_length=20, null=True)),
                ('harvest', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jica.District')),
            ],
        ),
        migrations.AddField(
            model_name='parish',
            name='sub_county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jica.Subcounty'),
        ),
        migrations.AddField(
            model_name='officer',
            name='parish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jica.Parish'),
        ),
        migrations.AddField(
            model_name='officer',
            name='subcounty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jica.Subcounty'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='parish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jica.Parish'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='subcounty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jica.Subcounty'),
        ),
    ]
