# Generated by Django 2.1.7 on 2019-04-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parish',
            old_name='subcounty',
            new_name='sub_county',
        ),
        migrations.RenameField(
            model_name='subcounty',
            old_name='subcounty',
            new_name='district',
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parish',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
